### ISSUE TITLE
RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by nangongliufeng** [autonomousvision/sdfstudio#103]
Thanks for your great work, how to solve this problem?
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
Setting up training dataset...
Caching all 49 images.
Setting up evaluation dataset...
Caching all 49 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
outputs/neus-facto-dtu65/neus-facto/2023-05-02_105138/sdfstudio_models/step-000020000.ckpt
Extract mesh with marching cubes and may take a while
(sdfstudio) root@1f9dcb330b47:~/code-jcc/sdfstudio# ns-export tsdf --load-config outputs/neus-facto-dtu65/neus-facto/2023-05-02_105138/config.yml --output-dir tsdf-meshes              
Setting up training dataset...
Caching all 49 images.
Setting up evaluation dataset...
Caching all 49 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
outputs/neus-facto-dtu65/neus-facto/2023-05-02_105138/sdfstudio_models/step-000020000.ckpt
☁ Computing rgb and depth images ☁ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1.54 fps 00:32
Integrating the TSDF
Traceback (most recent call last):
  File "/root/anaconda3/envs/sdfstudio/bin/ns-export", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/code-jcc/sdfstudio/scripts/exporter.py", line 328, in entrypoint
    tyro.cli(tyro.conf.FlagConversionOff[Commands]).main()
  File "/root/code-jcc/sdfstudio/scripts/exporter.py", line 140, in main
    tsdf_utils.export_tsdf_mesh(
  File "/root/code-jcc/sdfstudio/nerfstudio/exporter/tsdf_utils.py", line 341, in export_tsdf_mesh
    tsdf.integrate_tsdf(
  File "/root/code-jcc/sdfstudio/nerfstudio/exporter/tsdf_utils.py", line 209, in integrate_tsdf
    voxel_cam_coords[:, 2, :] = -voxel_cam_coords[:, 2, :]

**Comment by niujinshuchong** [comment]
Hi, you could use `ns-extract-mesh` to extract the mesh.
