### ISSUE TITLE
Add upgrade suggestion in Readme?

### ISSUE THREAD

**Issue by ZiyangYan** [autonomousvision/sdfstudio#145]
I merged the new version sdfstudio through pycharm, and run
---------------------------------------------------
pip install --upgrade pip setuptools
pip install -e .
ns-install-cli
-----------------------------------------
to upgrade the packages,
but when I executed **"ns-install-cli"**
**it raised a error:
"
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ns-train', '--tyro-print-completion', 'bash']' returned non-zero exit status 1.
"**
and then when I input **"ns-train -h"**, the result is:

**Traceback (most recent call last):
  File "/media/zyan/sandiskSSD/anaconda3/envs/sdfstudio/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/media/zyan/sandiskSSD/NeRF_methods/sdfstudio/scripts/train.py", line 52, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/media/zyan/sandiskSSD/NeRF_methods/sdfstudio/nerfstudio/configs/method_configs.py", line 134, in <module>
    sdf_field=SDFFieldConfig(
TypeError: __init__() got an unexpected keyword argument 'use_numerical_gradients'**

**Comment by niujinshuchong** [comment]
Hi, I don't have this error. Did you pull the latest code? You only need to install the environment once and after that, you can run `ns-install-cli` to update the command line completion without rerunning `pip install -e .`.
