### ISSUE TITLE
ns-render --traj interpolate

### ISSUE THREAD

**Issue by MvWouden** [autonomousvision/sdfstudio#156]
**Is your feature request related to a problem? Please describe.**
I would love to be able to use `ns-render` with `--traj interpolate`.
Currently only `spiral` and `filename` are supported.

`ns-render-mesh` does support `--traj interpolate`, as well as `spiral`, `filename`, `interpolate`, `ellipse`.

**Describe the solution you'd like**
Implement `--traj interpolate` for `ns-render` just like it is done for `ns-render-mesh`.
Perhaps implementing `ellipse` as well may make sense to have both `ns-render` and `ns-render-mesh` offer the same options (I personally don't need it atm though).

**Comment by MvWouden** [comment]
After trying to implement `--traj interpolate` for `ns-render` as how camera path interpolation is performed for `ns-render-mesh`, I get the following issue:

Command:
```
ns-render --traj interpolate --load-config <path/to/config> --output-path <path/to/out> --output-format images nerfstudio-data --data <path/to/data> --orientation-method none --no-center-poses --no-auto-scale-poses
```

Trace:
```
Traceback (most recent call last):
  File "/home/milanvw/Projects/sdfstudio/venv/bin/ns-render", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/milanvw/Projects/sdfstudio/scripts/render.py", line 208, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "/home/milanvw/Projects/sdfstudio/scripts/render.py", line 194, in main
    _render_trajectory_video(
  File "/home/milanvw/Projects/sdfstudio/scripts/render.py", line 113, in _render_trajectory_video
    outputs = pipeline.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/home/milanvw/Projects/sdfstudio/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/models/base_model.py", line 180, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/models/base_surface_model.py", line 250, in get_outputs
    samples_and_field_outputs = self.sample_and_forward_field(ray_bundle=ray_bundle)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/models/bakedsdf.py", line 242, in sample_and_forward_field
    field_outputs = self.field(ray_samples)
  File "/home/milanvw/Projects/sdfstudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/fields/sdf_field.py", line 617, in forward
    field_outputs = self.get_outputs(ray_samples, return_alphas=return_alphas, return_occupancy=return_occupancy)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/fields/sdf_field.py", line 571, in get_outputs
    h = self.forward_geonetwork(inputs)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/fields/sdf_field.py", line 362, in forward_geonetwork
    pe = self.position_encoding(inputs)
  File "/home/milanvw/Projects/sdfstudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/milanvw/Projects/sdfstudio/nerfstudio/field_components/encodings.py", line 192, in forward
    scaled_inputs = torch.matmul(in_tensor, self.P.to(in_tensor.device))[..., None] * freqs
RuntimeError: expected scalar type Double but found Float
``

**Comment by MvWouden** [comment]
> Hi, sorry for the late reply as I am out of work of 2 weeks. Could you track down the dtype of the tensors in this line `scaled_inputs = torch.matmul(in_tensor, self.P.to(in_tensor.device))[..., None] * freqs`. Would be great if you can also share how you implement it.

Hi, thanks for your reply. I had gotten further by casting the data types (to either float or double), but ultimately the process was  slow or got stuck. I ended up using a workaround with `ns-eval` to suit my purposes which worked a lot better, so this issue can possibly be closed.

**Comment by MvWouden** [comment]
> Hi, thanks for sharing your solution but I don't get why `ns-eval` is not slow if `ns-render` is? They are just loading the camera and rendering the images. So it should be similar, no?

I assume it's fully down to the changes I had to make to get `ns-render` working. So yes, they normally are the same speed.
