### ISSUE TITLE
assertion error when ns-install-cli 

### ISSUE THREAD

**Issue by iszihan** [autonomousvision/sdfstudio#165]
I get the following error when running ns-install-cli 

`Traceback (most recent call last):
  File "/opt/conda/envs/sdfstudio/bin/ns-install-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/localssd/sdfstudio/scripts/completions/install.py", line 284, in entrypoint
    tyro.cli(main, description=__doc__)
  File "/opt/conda/envs/sdfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 177, in cli
    output = _cli_impl(
  File "/opt/conda/envs/sdfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 432, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/opt/conda/envs/sdfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 215, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/mnt/localssd/sdfstudio/scripts/completions/install.py", line 276, in main
    _update_rc(completions_dir, mode, shell)
  File "/mnt/localssd/sdfstudio/scripts/completions/install.py", line 177, in _update_rc
    assert source_file.endswith(f"/completions/setup.{shell}")
AssertionError`

**Comment by niujinshuchong** [comment]
Hi, could you post the full trace. Don't know what's happening.
