### ISSUE TITLE
ns-extract-mesh not working with custom data

### ISSUE THREAD

**Issue by peta-peta** [autonomousvision/sdfstudio#168]
Hello, I am facing a problem with creating a mesh using a trained model with nerfstudio that comes along sdfstudio. The model is training properly and I am able to get the checkpoints. Unfortunately, I am not successful in getting a mesh at all. I do confirm that the ns-export-mesh application is running with the sculp tutorial that is attached to the tutorials.

Has anyone of you succeeded to create mehes on your own trained data? If yes, could you please share with me your working steps?

Thank you
Peter

**Comment by peta-peta** [comment]
I have run successfully the "poster" test case with nerfstudio v.0.3.2 and created a trained nerf model.
I tried to use ns-extract-mesh with this trained model from nerfstudio v.0.3.2 and got this errror:

`(sdfstudio1) peter@x3:~/Libraries/sdfstudio$ ns-extract-mesh --load-config ../nerfstudio-o3d-16/nerfstudio/outputs/poster/nerfacto/2023-07-19_133253/config.yml     --output-path meshes/test.ply
Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/sdfstudio1/bin/ns-extract-mesh", line 5, in <module>
    from scripts.extract_mesh import entrypoint
  File "/home/peter/Libraries/sdfstudio/scripts/extract_mesh.py", line 15, in <module>
    from nerfstudio.model_components.ray_samplers import save_points
ImportError: cannot import name 'save_points' from 'nerfstudio.model_components.ray_samplers' (/home/peter/Libraries/nerfstudio-o3d-16/nerfstudio/nerfstudio/model_components/ray_samplers.py)
`

Anyone of you can shed some light on it? Can I use trained model from nerfstudio v0.3.2 and create a mesh with sdfstudio?

Cheers
Peter

**Comment by peta-peta** [comment]
Thanks for your answer.

My understanding is that sdfstudio uses an older version of nerfstudio to create the nerf model. Sdfstudio just comes with an additional layer to extract surfaces from nerf models.

So, you are saying that training a model with sdfstudio uses a modified version of nerfstudio? And only nerf models trained by this particular version can be used with ns-extraxt-mesh, right?

**Comment by niujinshuchong** [comment]
@peta-peta SDFStudio implemented many sdf-based methods such as volsdf which are designed for surface reconstruction. You need to train your own model with SDFStudio and then extract the mesh from the sdf field.

**Comment by peta-peta** [comment]
Got it! Thanks for your answer and confirming my understanding.

In the meantime I made further progress on my own and was able to use sdfstudio and extract meshes.

However, I came to the same conclusion as some other guys In this forum. Using the sdf based methods such as neus-facto. Does not yield good results. Using my own custom data with nerfacto, I get a  nicely rendered model in the viewer. I compared the results after 20k iterations.

- Do I need more iterations with sdf based methods!
- Do I need more gpu memory with sdf based methods? I currently have only 8 GB but I will get soon additional 24 GB.
- Could I start training with non-sdf based methods and use the checkpoint of the pretrained model as initial condition for sdf based method, such as neus-facto?
- people in this forum say that sdf based methods are more unstable and harder to converge. How can I investigate in a simple plot during the training if my model is converging or not?

Cheers Peter

**Comment by niujinshuchong** [comment]
Hi, in general SDF based methods use more iterations and are also slower and needs more GPU memory since it needs to compute the gradient for eikonal regularization and appearance network. 

Yes, using a pretrained nerfacto model as initialization for SDF is a very promising idea, and I wanted to try it out but unfortunately couldn't find the time (https://github.com/autonomousvision/sdfstudio/issues/133#issuecomment-1603204173). Please let me know if you can get some good results. 

For neus-facto, you could check the plots of these values https://github.com/autonomousvision/sdfstudio/blob/master/nerfstudio/models/neus.py#L117-L118. If s_val increases along the training and reaches >500, it usually indicates it converges well.

**Comment by peta-peta** [comment]
I used a pretrained model using nerfacto and used it as starting point for ns-train neus-facto:
Unfortunately, it gave me this error:

```
Sending ping to the viewer Bridge Server...
Successfully connected.
[NOTE] Not running eval iterations since only viewer is enabled. Use --vis wandb or --vis tensorboard to run with eval 
instead.
Disabled tensorboard/wandb event writers
Setting up training dataset...
Caching all 210 images.
Setting up evaluation dataset...
Caching all 210 images.
/home/peter/.local/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:61: FutureWarning: Importing `PeakSignalNoiseRatio` from `torchmetrics` was deprecated and will be removed in 2.0. Import `PeakSignalNoiseRatio` from `torchmetrics.image` instead.
  _future_warning(
Loading latest checkpoint from load_dir
Printing profiling stats, from longest to shortest duration in seconds
Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/sdfstudio1/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/peter/Libraries/sdfstudio/scripts/train.py", line 250, in entrypoint
    main(
  File "/home/peter/Libraries/sdfstudio/scripts/train.py", line 236, in main
    launch(
  File "/home/peter/Libraries/sdfstudio/scripts/train.py", line 175, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/peter/Libraries/sdfstudio/scripts/train.py", line 89, in train_loop
    trainer.setup()
  File "/home/peter/Libraries/sdfstudio/nerfstudio/engine/trainer.py", line 120, in setup
    self._load_checkpoint()
  File "/home/peter/Libraries/sdfstudio/nerfstudio/engine/trainer.py", line 268, in _load_checkpoint
    self.pipeline.load_pipeline(loaded_state["pipeline"])
  File "/home/peter/Libraries/sdfstudio/nerfstudio/pipelines/base_pipeline.py", line 439, in load_pipeline
    self.load_state_dict(state)  # type: ignore
  File "/home/peter/anaconda3/envs/sdfstudio1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VanillaPipeline:
	Missing key(s) in state_dict: "_model.field_background", "_model.field.encoding.params", "_model.field.glin0.bias", "_model.field.glin0.weight_g", "_model.field.glin0.weight_v", "_model.field.glin1.bias", "_model.field.glin1.weight_g", "_model.field.glin1.weight_v", "_model.field.glin2.bias", "_model.field.glin2.weight_g", "_model.field.glin2.weight_v", "_model.field.laplace_density.beta_min", "_model.field.laplace_density.beta", "_model.field.deviation_network.variance", "_model.field.clin0.bias", "_model.field.clin0.weight_g", "_model.field.clin0.weight_v", "_model.field.clin1.bias", "_model.field.clin1.weight_g", "_model.field.clin1.weight_v", "_model.field.clin2.bias", "_model.field.clin2.weight_g", "_model.field.clin2.weight_v". 
	Unexpected key(s) in state_dict: "datamanager.train_camera_optimizer.pose_adjustment", "datamanager.train_ray_generator.pose_optimizer.pose_adjustment", "datamanager.eval_ray_generator.pose_optimizer.pose_adjustment", "_model.field.mlp_base.params", "_model.field.mlp_head.params", "_model.field.position_encoding.params", "_model.field.direction_encoding.params". 


```
