### ISSUE TITLE
CUDA out of  memory

### ISSUE THREAD

**Issue by Wei-Qi** [autonomousvision/sdfstudio#182]
I use the neus-facto to train my custom dataset, and images in data are so big(resolution 4024*3036). When evaluating, CUDA is out of  memory.(I use two RTX-3090).
This is my command:
```
CUDA_VISIBLE_DEVICES=5,6 ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis tensorboard --experiment-name neus-facto-pianzhen  --machine.num-gpus 2 --pipeline.datamanager.train-num-rays-per-batch 1024 --pipeline.datamanager.eval-num-rays-per-batch 512 --pipeline.model.sdf-field.bias 0.1 --pipeline.model.background-model mlp  --pipeline.model.background-color white sdfstudio-data --data /data/user/dataset/pianzhen_fixed_studio
```
the report error:
```
Traceback (most recent call last):
  File "/data/user/miniconda3/envs/sdfstudio/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/user/sdfstudio/scripts/train.py", line 143, in _distributed_worker
    output = main_func(local_rank, world_size, config, global_rank)
  File "/data/user/sdfstudio/scripts/train.py", line 90, in train_loop
    trainer.train()
  File "/data/user/sdfstudio/nerfstudio/engine/trainer.py", line 174, in train
    self.eval_iteration(step)
  File "/data/user/sdfstudio/nerfstudio/utils/decorators.py", line 70, in wrapper
    ret = func(self, *args, **kwargs)
  File "/data/user/sdfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/data/user/sdfstudio/nerfstudio/engine/trainer.py", line 349, in eval_iteration
    metrics_dict, images_dict = self.pipeline.get_eval_image_metrics_and_images(step=step)
  File "/data/user/sdfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/data/user/sdfstudio/nerfstudio/pipelines/base_pipeline.py", line 311, in get_eval_image_metrics_and_images
    outputs = self.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/data/user/miniconda3/envs/sdfstudio/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/user/sdfstudio/nerfstudio/models/base_model.py", line 188, in get_outputs_for_camera_ray_bundle
    outputs[output_name] = torch.cat(outputs_list).view(image_height, image_width, -1)  # type: ignore
RuntimeError: CUDA out of memory. Tried to allocate 6.55 GiB (GPU 1; 23.70 GiB total capacity; 14.58 GiB already allocated; 5.05 GiB free; 16.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
How can I fix this problem?

Thank you!

**Comment by niujinshuchong** [comment]
Hi, maybe you could comment out this line (https://github.com/autonomousvision/sdfstudio/blob/master/nerfstudio/models/base_surface_model.py#L306C13-L306C13) as it save all the sampled points on the ray and these points is only used for visibility computation in bakedsdf's mesh-extraction.
