### ISSUE TITLE
An error occurs when using ns-export poisson to export. What is the cause

### ISSUE THREAD

**Issue by 440981** [autonomousvision/sdfstudio#213]
The model is trained with the following commands
```
ns-train monosdf --pipeline.model.sdf-field.inside-outside True \
--trainer.load-dir outputs/-mnt-workspace-sdfstudio-data-goal-beizi/monosdf/2023-08-29_093436/sdfstudio_models/ \
nerfstudio-data --data /mnt/workspace/sdfstudio/data/goal/beizi/
```
Fetch command is
```
ns-export poisson --load-config outputs/-mnt-workspace-sdfstudio-data-goal-beizi/monosdf/2023-08-29_093436/config.yml \
--output-dir meshes/
```
```
[09:12:45] Auto image downscale factor of 2                                                 nerfstudio_dataparser.py:293
           Skipping 0 files in dataset split train.                                         nerfstudio_dataparser.py:148
           Skipping 0 files in dataset split test.                                          nerfstudio_dataparser.py:148
Setting up training dataset...
Caching all 357 images.
Setting up evaluation dataset...
Caching all 39 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
outputs/-mnt-workspace-sdfstudio-data-goal-beizi/monosdf/2023-08-29_093436/sdfstudio_models/step-000199999.ckpt
Checking that the pipeline has a normal output.
Traceback (most recent call last):
  File "/opt/conda/envs/sdfstudio/bin/ns-export", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/workspace/sdfstudio/scripts/exporter.py", line 328, in entrypoint
    tyro.cli(tyro.conf.FlagConversionOff[Commands]).main()
  File "/mnt/workspace/sdfstudio/scripts/exporter.py", line 245, in main
    self.validate_pipeline(pipeline)
  File "/mnt/workspace/sdfstudio/scripts/exporter.py", line 224, in validate_pipeline
    outputs = pipeline.model(ray_bundle)
  File "/opt/conda/envs/sdfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/sdfstudio/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/mnt/workspace/sdfstudio/nerfstudio/models/base_surface_model.py", line 291, in get_outputs
    depth = depth / ray_bundle.directions_norm
TypeError: unsupported operand type(s) for /: 'Tensor' and 'NoneType'
```

**Comment by niujinshuchong** [comment]
Hi, you should use `ns-extract-mesh` to export the mesh since it is a sdf-based method.

**Comment by 440981** [comment]
Thanks for your reply, I know why.
