### ISSUE TITLE
Neus Training failed on Blender Dataset downloaded from the nerfstudio website 

### ISSUE THREAD

**Issue by iszihan** [autonomousvision/sdfstudio#221]
Hello, I'm trying to run neus on the blender dataset (ficus and drums more specifically). When running on Ficus, I see relatively reasonable result in the first few evaluation iterations, but later at step 2500, I get this error for the accumulation image. Does this mean the training failed? What could be the reason for it? My training command is `ns-train neus --vis tensorboard blender-data --data ../data/blender/ficus` -- makes me wonder if sdfstudio support blender dataparser? If not, what's a good way to convert it to a format sdfstudio supports? Thank you in advance! 

`Traceback (most recent call last):
  File "/home/zling/anaconda3/envs/sdfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/scripts/train.py", line 250, in entrypoint
    main(
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/scripts/train.py", line 236, in main
    launch(
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/scripts/train.py", line 175, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/scripts/train.py", line 90, in train_loop
    trainer.train()
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/engine/trainer.py", line 174, in train
    self.eval_iteration(step)
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/utils/decorators.py", line 70, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/engine/trainer.py", line 349, in eval_iteration
    metrics_dict, images_dict = self.pipeline.get_eval_image_metrics_and_images(step=step)
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/pipelines/base_pipeline.py", line 312, in get_eval_image_metrics_and_images
    metrics_dict, images_dict = self.model.get_image_metrics_and_images(outputs, batch)
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/models/base_surface_model.py", line 486, in get_image_metrics_and_images
    acc = colormaps.apply_colormap(outputs["accumulation"])
  File "/home/zling/Documents/projects/shellnerf/sdfstudio/nerfstudio/utils/colormaps.py", line 42, in apply_colormap
    assert image_long_min >= 0, f"the min value is {image_long_min}"
AssertionError: the min value is -9223372036854775808`

**Comment by iszihan** [comment]
![image](https://github.com/autonomousvision/sdfstudio/assets/36280571/e75cd3c8-c752-4dc2-97cf-4de00936c6a2)
Here are the evaluation images from step 2000.

**Comment by iszihan** [comment]
Adding the flags in this [issue's](https://github.com/autonomousvision/sdfstudio/issues/117) training command helped.
