### ISSUE TITLE
Instant NGP is divergent from NeRFStudio

### ISSUE THREAD

**Issue by joeylitalien** [autonomousvision/sdfstudio#25]
**Describe the bug**
The model `NGPModel` is divergent from the one found in [NeRFStudio](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/models/instant_ngp.py). This raises an issue due to incompatibility with newer NerfAcc version (i.e. `nerfacc.unpack_info()`).

**To Reproduce**
1. Install SDFStudio.
2. Run `ns-train instant-ngp sdfstudio-data --data data/sdfstudio-demo-data/replica-room0`.

**Expected behavior**
Regular training.

**Screenshots**
```
Traceback (most recent call last):
  File "/home/joey/venvs/sdfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/joey/code/sdfstudio/scripts/train.py", line 248, in entrypoint
    main(
  File "/home/joey/code/sdfstudio/scripts/train.py", line 234, in main
    launch(
  File "/home/joey/code/sdfstudio/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/joey/code/sdfstudio/scripts/train.py", line 88, in train_loop
    trainer.train()
  File "/home/joey/code/sdfstudio/nerfstudio/engine/trainer.py", line 151, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/joey/code/sdfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/home/joey/code/sdfstudio/nerfstudio/engine/trainer.py", line 318, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/joey/code/sdfstudio/nerfstudio/pipelines/dynamic_batch.py", line 78, in get_train_loss_dict
    model_outputs, loss_dict, metrics_dict = super().get_train_loss_dict(step)
  File "/home/joey/code/sdfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/home/joey/code/sdfstudio/nerfstudio/pipelines/base_pipeline.py", line 260, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)
  File "/home/joey/venvs/sdfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joey/code/sdfstudio/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/home/joey/code/sdfstudio/nerfstudio/models/instant_ngp.py", line 171, in get_outputs
    ray_samples, packed_info, ray_indices = self.sampler(
  File "/home/joey/venvs/sdfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joey/code/sdfstudio/nerfstudio/model_components/ray_samplers.py", line 481, in forward
    ray_indices = nerfacc.unpack_info(packed_info)
  File "/home/joey/venvs/sdfstudio/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: unpack_info() missing 1 required positional argument: 'n_samples'
```

**Additional context**
I tried hotfixing the error by updating problematic methods in `models/instant_ngp.py` and `model_components/ray_samplers.py`. While it can run, the results are not great, which makes me doubt that this was done correctly. Instant-NGP is not an SDF-based technique, but it would be nice to not have to also have NeRFStudio installed to run it for e.g. comparison baselines.

**Comment by niujinshuchong** [comment]
Hi, thanks for reporting this. I updated the instant-ngp code use latest nerfacc and it works well in replica dataset if you set the near and far plane correctly as follows
```bash
ns-train instant-ngp --pipeline.model.cone-angle 0.0 --pipeline.model.near-plane 0.05 --pipeline.model.far-plane 2.5 --pipeline.model.alpha-thre 0.0 sdfstudio-data --data data/sdfstudio-demo-data/replica-room0 
```

I get the result like this
![Screenshot from 2023-01-11 19-44-29](https://user-images.githubusercontent.com/13434986/211893747-1271fcf8-ec16-4507-ae9c-39dcd1a465d0.png)

**Comment by joeylitalien** [comment]
Awesome! The near-far planes were off, hence the bad results. Thanks for the commit :)
