### ISSUE TITLE
Server connected, Render disconnected

### ISSUE THREAD

**Issue by AliKaramiFBK** [autonomousvision/sdfstudio#31]
Hi 
I want to visualize my model using viewer tool. accessing through the link provided belove the training part but the issues as you can see in the following pic, server is connected but render is disconnected 
what can  be the issue 
so I can only see the image orientation and not the 3D model.

![image](https://user-images.githubusercontent.com/58226230/213216376-77ff06c8-39bb-417c-b5c9-c6227176c6da.png)

**Comment by niujinshuchong** [comment]
Hi, please refer to https://github.com/nerfstudio-project/nerfstudio/issues/765

**Comment by yzslab** [comment]
I met the same problem. When I open the viewer page, below Exception message are printed in the console:
![Untitled.png](https://s2.loli.net/2023/01/24/V7Fco1GC5Jpi4Uk.png)

**Comment by yzslab** [comment]
> I met the same problem. When I open the viewer page, below Exception message are printed in the console: ![Untitled.png](https://camo.githubusercontent.com/d73a5979a724ad42513d3521ac0192277ae97c9af0852ae79e125c6521285660/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30312f32342f563746636f314743354a706934556b2e706e67)

```pip install cryptography==2.8``` can fix this Exception.

**Comment by lexvandersluijs** [comment]
Thanks yzslab. In my case it keeps saying "Render disconnected" but the image does appear, so the problem is >60% fixed with that.

**Comment by niujinshuchong** [comment]
@AliKaramiFBK Do you still have the problem? Your images have black background, maybe you could use '--pipeline.model.background-color black'.

**Comment by tlightsky** [comment]
I meet same issue following README:
![image](https://user-images.githubusercontent.com/429211/223493699-7a9d1a55-bc4d-4537-b902-6c9c18ad61cd.png)

**Comment by niujinshuchong** [comment]
@tlightsky Maybe you could try
```bash
pip uninstall -y cryptography
pip install cryptography==38
```

Maybe also try to use https://viewer.nerf.studio to use the latest version.

**Comment by tlightsky** [comment]
> @tlightsky Maybe you could try
> 
> ```shell
> pip uninstall -y cryptography
> pip install cryptography==38
> ```
> 
> Maybe also try to use https://viewer.nerf.studio to use the latest version.

No luck
```
Viewer at: https://viewer.nerf.studio/versions/22-12-02-0/?websocket_url=ws://localhost:7007
Exception in thread Thread-100:
Traceback (most recent call last):
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\source\py\sdfstudio\nerfstudio\viewer\server\viewer_utils.py", line 365, in loop_in_thread
    loop.run_until_complete(self.send_webrtc_answer(data))
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:\source\py\sdfstudio\nerfstudio\viewer\server\viewer_utils.py", line 551, in send_webrtc_answer
    await pc.setLocalDescription(answer)
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aiortc\rtcpeerconnection.py", line 783, in setLocalDescription
    await self.__gather()
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aiortc\rtcpeerconnection.py", line 1023, in __gather    await asyncio.gather(*coros)
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aiortc\rtcicetransport.py", line 201, in gather
    await self._connection.gather_candidates()
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aioice\ice.py", line 417, in gather_candidates
    for candidates in await asyncio.gather(*coros):
  File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aioice\ice.py", line 887, in get_component_candidates
```

**Comment by tlightsky** [comment]
> > @tlightsky Maybe you could try
> > ```shell
> > pip uninstall -y cryptography
> > pip install cryptography==38
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe also try to use https://viewer.nerf.studio to use the latest version.
> 
> No luck
> 
> ```
> Viewer at: https://viewer.nerf.studio/versions/22-12-02-0/?websocket_url=ws://localhost:7007
> Exception in thread Thread-100:
> Traceback (most recent call last):
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "E:\source\py\sdfstudio\nerfstudio\viewer\server\viewer_utils.py", line 365, in loop_in_thread
>     loop.run_until_complete(self.send_webrtc_answer(data))
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\asyncio\base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "E:\source\py\sdfstudio\nerfstudio\viewer\server\viewer_utils.py", line 551, in send_webrtc_answer
>     await pc.setLocalDescription(answer)
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aiortc\rtcpeerconnection.py", line 783, in setLocalDescription
>     await self.__gather()
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aiortc\rtcpeerconnection.py", line 1023, in __gather    await asyncio.gather(*coros)
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aiortc\rtcicetransport.py", line 201, in gather
>     await self._connection.gather_candidates()
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aioice\ice.py", line 417, in gather_candidates
>     for candidates in await asyncio.gather(*coros):
>   File "E:\Users\wangc\miniconda3\envs\sdfstudio\lib\site-packages\aioice\ice.py", line 887, in get_component_candidates
> ```

Wait, seems Ok after 1k step
