### ISSUE TITLE
Can't use the viewer

### ISSUE THREAD

**Issue by tsugg** [autonomousvision/sdfstudio#52]
Everything seems to be going right until I click on the link to the viewer

![image](https://user-images.githubusercontent.com/48035539/223510025-3d3d7ea7-be68-4c06-8c03-0aa1c4b71ff2.png)

I get this stack trace :

Viewer at: https://viewer.nerf.studio/versions/22-12-02-0/?websocket_url=ws://localhost:7007
Exception in thread Thread-16 (loop_in_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tommysugg/sdfstudio/nerfstudio/viewer/server/viewer_utils.py", line 365, in loop_in_thread
    loop.run_until_complete(self.send_webrtc_answer(data))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/tommysugg/sdfstudio/nerfstudio/viewer/server/viewer_utils.py", line 546, in send_webrtc_answer

And the log says something different : 

ZMQWebSocketBridge using zmq_port="58147" and websocket_port="7007"
opened: <__main__.WebSocketHandler object at 0x7fa11e984ac0>
Sending entire scene state due to websocket connection established.
closed: <__main__.WebSocketHandler object at 0x7fa11e984ac0>

I've tried on many of the models and this happens

**Comment by niujinshuchong** [comment]
Hi, please refer to https://github.com/nerfstudio-project/nerfstudio/issues/765.

Maybe you could try
```bash
pip uninstall -y cryptography
pip install cryptography==38
```

Maybe also try to use https://viewer.nerf.studio to use the latest version.

**Comment by tsugg** [comment]
works! thank you!
